---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  become: no
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "nikhilguptaiiitb/scientific-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
#    - name: Running container
#      shell: docker run -it -d --name scientific_calculator nikhilguptaiiitb/scientific-calculator