---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  become: no
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "nikhilguptaiiitb/scientific-calculator"
        state: present

    - name: Run Docker Container
      docker_container:
        name: scientific_calculator
        image: "nikhilguptaiiitb/scientific-calculator"
        state: started
        published_ports:
          - "8081:8080"
        restart_policy: always